const sidebarConfig = [
  {
    label: "Dashboard",
    icon: "Home",
    path: "/dashboard/admin",
    roles: ["admin"],
    expandable: false,
  },
  {
    label: "Dashboard",
    icon: "School",
    path: "/dashboard/teacher",
    roles: ["teacher"],
    expandable: false,
  },
  {
    label: "Dashboard",
    icon: "SupervisorAccount",
    path: "/dashboard/mentor",
    roles: ["mentor"],
    expandable: false,
  },
  {
    label: "Dashboard",
    icon: "Work",
    path: "/dashboard/hr",
    roles: ["hr"],
    expandable: false,
  },
  {
    label: "Boards",
    icon: "ViewComfy",
    path: "/dashboard/boards",
    roles: ["admin"],
    expandable: false,
  },
  {
    label: "Subjects",
    icon: "School",
    path: "/dashboard/subjects",
    roles: ["admin"],
    expandable: false,
  },
  {
    label: "Students",
    icon: "People",
    roles: ["admin"],
    expandable: true,
    subItems: [
      { label: "List Students", path: "students" },
      { label: "Add Student", path: "addStudent" },
    ],
  },
  {
    label: "Teachers",
    icon: "Person",
    roles: ["admin"],
    expandable: true,
    subItems: [
      { label: "List Teachers", path: "teachers" },
      { label: "Add Teacher", path: "addTeacher" },
    ],
  },
  {
    label: "Courses",
    icon: "LibraryBooks",
    roles: ["admin"],
    expandable: true,
    subItems: [
      { label: "List Courses", path: "courses" },
      { label: "Add Course", path: "addCourse" },
    ],
  },
  {
    label: "Reports",
    icon: "Assessment",
    roles: ["admin"],
    expandable: true,
    subItems: [
      { label: "Student Report", path: "student-report" },
      { label: "Teacher Report", path: "teacher-report" },
    ],
  },
  {
    label: "Purchases",
    icon: "ShoppingCart",
    path: "course-purchase-list",
    roles: ["admin"],
    expandable: false,
  },
  {
    label: "Sales Mentor",
    icon: "PeopleOutline",
    path: "sales-mentor-list",
    roles: ["admin"],
    expandable: false,
  },
  {
    label: "Lead Manager",
    icon: "Settings",
    path: "lead-manager",
    roles: ["admin"],
    expandable: false,
  },
  {
    label: "Doubts",
    icon: "Chat",
    path: "doubts",
    roles: ["admin"],
    expandable: false,
  },
  {
    label: "Enquiries",
    icon: "Notifications",
    path: "enquiry",
    roles: ["admin"],
    expandable: false,
  },
  {
    label: "Banners",
    icon: "Image",
    path: "banners",
    roles: ["admin"],
    expandable: false,
  },
  {
    label: "Registration",
    icon: "Image",
    path: "registration",
    roles: ["admin"],
    expandable: false,
  },
  {
    label: "Push Notification",
    icon: "NotificationsActive",
    path: "pushNotification",
    roles: ["admin"],
    expandable: false,
  },
  {
    label: "Assigned Courses",
    icon: "LibraryBooks",
    path: "enrolled-courses",
    roles: ["teacher"],
    expandable: false,
  },
  {
    label: "Add Class",
    icon: "AddCircle",
    path: "add-class",
    roles: ["teacher"],
    expandable: false,
  },
  {
    label: "Chats",
    icon: "ChatBubble",
    path: "Chats",
    roles: ["teacher"],
    expandable: false,
  },
  {
    label: "Group Chats",
    icon: "Group",
    path: "group-chat",
    roles: ["teacher"],
    expandable: false,
  },
  {
    label: "Doubts",
    icon: "LiveHelp",
    path: "doubtscreen",
    roles: ["teacher"],
    expandable: false,
  },
  {
    label: "My Leaves",
    icon: "EventAvailable",
    path: "myleaves",
    roles: ["teacher"],
    expandable: false,
  },
  {
    label: "Teachers List",
    icon: "GroupWork",
    path: "teachersList",
    roles: ["hr"],
    expandable: false,
  },
  {
    label: "Mentor List",
    icon: "SupervisorAccount",
    path: "mentorList",
    roles: ["hr"],
    expandable: false,
  },
  {
    label: "Mentor Leaves",
    icon: "EventBusy",
    path: "mentorLeaves",
    roles: ["hr"],
    expandable: false,
  },
  {
    label: "Teacher Leaves",
    icon: "EventBusy",
    path: "teacherLeaves",
    roles: ["hr"],
    expandable: false,
  },
  {
    label: "My Leaves",
    icon: "EventAvailable",
    path: "mentorLeaveRequest",
    roles: ["mentor"],
    expandable: false,
  },
  {
    label: "Change Password",
    icon: "Lock",
    path: "change-password",
    roles: ["teacher"],
    expandable: false,
  },
  {
    label: "Logout",
    icon: "ExitToApp",
    path: "/",
    roles: ["teacher", "admin", "mentor", "hr"],
    expandable: false,
  },
 
];

export default sidebarConfig;
